title: Vardaan's CSA 
owner_name: Nighthawk Coders
github_username: nighthawkcoders
baseurl: "/vsstudent"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
future: true
utterances:
  repo: "nighthawkcoders/vsstudent"
  issue-term: "title"
  label: "utteranc.es"
  theme: "github-light"
